server:
  port: 8088

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/realms/FantaWeCom
          jwk-set-uri: http://localhost:7080/realms/FantaWeCom/protocol/openid-connect/certs


  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/db
    username: user
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: false


logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  auth:
    converter:
      principle-attribute: preferred_username
      resource-id: demo




