

spring:
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/db
    username: user
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: false

  security:
    debug: true

server:
  port: 8088


